import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Web3Provider } from "@/components/Web3Provider";
import Nav from "@/components/Nav";

import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const contents = {
  1: "How to provide different levels of security for different transactions? Imagine we want a wallet that offers different protection mechanisms depending on the type of transaction. For example, transfering ERC20s should require a regular 1 signature (like an EOA) but transferring any NFT should require 2 signatures, for extra protection. How could we do this? We can't use a regular EOA, since there is no way to require 2 signatures from an EOA. An EOA can always execute any transaction with a single signauture. So, we need a smart contract that can act as our wallet. This will be called a smart wallet.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Provider>
          <main className="h-screen w-full grid grid-cols-4">
            <div className="col-span-1 border-r bg-neutral-50 z-50 p-4">
              <Nav />
              <aside>
                <ul>
                  <li>
                    <Link href="/1">Part 1</Link>
                  </li>
                  <li>
                    <Link href="/2">Part 2</Link>
                  </li>
                  <li>
                    <Link href="/3">Part 3</Link>
                  </li>
                </ul>
              </aside>
              <div className="mt-4 text-neutral-700 text-sm leading-6">
                {contents[1]}
              </div>
            </div>
            <div className="col-span-3 graph-paper">
              <main className="h-full p-4">{children}</main>
            </div>
          </main>
        </Web3Provider>
      </body>
    </html>
  );
}
